### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by jackmellis** [madole/babel-strip-test-code#1]
Hi,

We use this extensively in our projects, but we're also looking to upgrade to Babel 7. Are there any plans to port this over?

**Comment by madole** [comment]
I haven't looked at this in a long time but I'll look into doing a 2.0 release for babel 7 when github sorts itself out.

**Comment by jackmellis** [comment]
After looking into this further I _think_ this was a red herring. I'm pretty sure this package still works.
